---
title: "TCG5"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

library(XML)
library(rvest)

weburl1<-read_html("https://www.loriferber.com/research/presidential-facts-statistics/presidential-birthdates.html")
weburl1


Name<-weburl1%>%html_nodes("td:nth-child(2) span")%>%html_text()
Name

Term<-weburl1%>%html_nodes("td:nth-child(3) span")%>%html_text()
Term


Place_of_birth<-weburl1%>%html_nodes("td:nth-child(4) span")%>%html_text()
Place_of_birth

Date_of_Birth<-weburl1%>%html_nodes("td:nth-child(5) span")%>%html_text()
format(Date_of_Birth, format="%m/%d/%Y")


Age_at_Inauguration<-weburl1%>%html_nodes("td:nth-child(7) span")%>%html_text()
Age_at_Inauguration



today <- Sys.Date()
format(today, format="%m/%d/%Y")

presidents_age_as_of_today_in_days<-floor(difftime((Sys.Date()),as.Date(Date_of_Birth,  "%m/%d/%Y"),unit="auto"))

presidents_age_as_of_today_in_days



US_Presidential_Info<-data.frame(Name,Term,Place_of_birth,Date_of_Birth,Age_at_Inauguration,presidents_age_as_of_today_in_days)

US_Presidential_Info


```
